apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nthu-data-api
  name: nthu-data-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nthu-data-api
  template:
    metadata:
      labels:
        app: nthu-data-api
    spec:
      containers:
        - image: gcr.io/nthu-chatbot/github.com/NTHU-SA/nthu-data-api
          name: nthu-data-api
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
              ephemeral-storage: 1Gi
              memory: "512Mi"
            limits:
              cpu: "250m"
              ephemeral-storage: 1Gi
              memory: "512Mi"
          env:
            - name: TZ
              value: Asia/Taipei
            - name: ENV
              value: production
            - name: LOGURU_LEVEL
              value: ERROR
            - name: PORT
              value: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: nthu-data-api
  labels:
    app: nthu-data-api
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - protocol: "TCP"
      port: 443
      targetPort: 5000
  selector:
    app: nthu-data-api
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nthu-data-api
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nthu-data-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
