name: Code formatter

on: [push]

jobs:
  linter_name:
    name: Code formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Format code with black and isort
        run: |
          pip install black isort
          isort .
          black .
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "style: Format code with black and isort"
          add: "."